# -*- coding: utf-8 -*-
"""Lab Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wGJMO47vv0BKwQj0BgrzrAwIDHzSd48l
"""

count=18
while count <=63:
  print(count, end=',')
  count=count+9

count= 24
while count>=-6:
  print(count, end=',')
  count=count-6
print('OUTSIDE LOOP',count)

count=-10
while count<=20:
  if count !=20:
    print(count,end=',')
  else:
    print(count)
  count= count+5

count= 24
while count>=-6:
  if count !=-6:
    print(count, end=',')
  else:
    print(count)
  count=count-6
print('OUTSIDE Loop', count)

count=18
while count<=63:
  if count%2==0:
    print(count, end=',')
  else:
    print('-'+ str(count), end=',')
  count=count+9

name=int(input('Please enter your name: '))
for count in range(1, name+1):
  print('Toyota')

total=0
for count in range(1, 601, 1):
  if (count%7==0 and count%9==0):
    total= total+count
print(total)

total=0
for count in range(1, 601, 1):
   if((count%7==0 and count%9!=0) or (count%7!=0 and count%9==0)):
       total= total+count
print(total)

count=0
for count in range(10,51,1):
  if(count%2!=0):
    print(count, end=' ')

n=10
Y=0
for count in range (1, n+1,1):
   if count%2==0:
     Y=Y-count**2
   else:
     Y=Y+count**2
print(Y)

test = 1
j = 0
k = 100
while (k > 0):
    while ( j < k ):
        test = k + j -21
        print( str(1 + int (test / 2)) + "32")
        j += 10
    k -= 10
test = 1
j = 0
k = 100

user_given= 32768
 
while user_given!=0:
  digit= user_given%10
  if user_given==3:
     print(digit, end='')
  print(digit, end=',')
user_given=user_given//10

count=int(input('please enter your number: '))
for count in range(1,11,1):  
  if count%2!=0:
     print(count)

number= int(input('Sir, please enter your number: '))

if 7%9==0 and 7%7==0:
  print()

sum=0
count=1
while count<=600:
    if count%7==0 and count%9==0:
      pass
    elif count%7==0 or count%9==0:
      sum=sum+count
    count=count+1
print(sum)

x = 0
p =0
sum = 0
p = 1
x = 2
q = None
sum = 0
while p < 12:
     q = x + p - (sum + 7 / 3) / 3.0 % 2
     sum = sum + x + int(q)
     x += 1
     print(sum)
     if x > 5:
        p += 4 / 2
     else:
        p += (3 % 1)
sum = int(sum + p)
print(sum)



x = 0
p = 0
sum = 0
p = 1
x = 2
q = 0.0
sum = 0
while (p < 10) :
    q = x + p - (sum + int(5 / 3)) / 3.0 % 2
    sum = sum + x + int(q)
    x += 1
    print(sum)
    if (x > 5) :
        p += int(4 / 2)
    else :
        p += 3 % 1
sum = sum + p
print(sum)

1+3%1

x = y = 0
sum = 0
while (x < 10):
    y = x - 3
    while (y < 3):
        sum = x - y * 2
        print(sum)
        y = y + 1
    if (x > 7):
         x += 1
    else:
         x += 3
sum = x - y * 2
print(sum)

count=1
sum=0
while count<=5:
      number=int(input('Please insert your number: '))
      sum=sum+number
      print(sum)
      count=count+1

count=1
total=0
machine=0
while count<=5:
      number=int(input('Please insert your number: '))
      if number%2==1:
          total=total+number
      machine=machine+1
      count=count+1
average=total/machine
print(total)
print(total)