# -*- coding: utf-8 -*-
"""Lab Assignment 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yd8EFVcJSnzTWXZolxAqa8un7rmcl-7r

Sorting
"""

'Hello this is Tasrif Coding'

#task-1:
my_list=[10, 1, 20, 3, 6, 2, 5, 11, 15, 2, 12, 14, 17, 18, 29]
for i in range(len(my_list)):
    for j in range(len(my_list)-i-1):
        if my_list[j]>my_list[j+1]:
            temp=my_list[j]
            my_list[j]=my_list[j+1]
            my_list[j+1]=temp
print(my_list)

#task-1:
my_list=[10, 1, 20, 3, 6, 2, 5, 11, 15, 2, 12, 14, 17, 18, 29]
for i in range(len(my_list)):
    for j in range(len(my_list)-i-1):
        if my_list[j]>my_list[j+1]:
            temp=my_list[j+1]
            my_list[j+1]=my_list[j]
            my_list[j]=temp
print(my_list)

def list1(my_tuple):
    my_list=list(my_tuple)
    for i in range(len(my_list)):
        for j in range(len(my_list)-i-1):
            if my_list[j]>my_list[j+1]:
                temp=my_list[j+1]
                my_list[j+1]=my_list[j]
                my_list[j]=temp

list1([10, 1, 20, 3, 6, 2, 5, 11, 15, 2, 12, 14, 17, 18, 29])
print(my_list)

"""Selection Sorting:"""

#task-2:
my_list= [10, 1, 20, 3, 6, 2, 5, 11, 15, 2, 12, 14, 17, 18, 29]
for i in range(len(my_list)):
    min=my_list[i]
    min_loc=i

    for j in range(i+1,len(my_list)):
        if min>my_list[j]:
            min=my_list[j]
            min_loc=j
    temp=min
    my_list[min_loc]=my_list[i]
    my_list[i]=temp
print(my_list)

#task-2:
my_list= [10, 1, 20, 3, 6, 2, 5, 11, 15, 2, 12, 14, 17, 18, 29]
for i in range(len(my_list)):
    min=my_list[i]
    min_loc=i

    for j in range(i+1,len(my_list)):
        if min>my_list[j]:
            min=my_list[j]
            min_loc=j
    temp=min
    print(temp)
    my_list[min_loc]=my_list[i]
    my_list[i]=temp
print(my_list)

#task-2:
a_list= [10, 1, 20, 3, 6, 2, 5, 11, 15, 2, 12, 14, 17, 18, 29]
def list1(my_list):
    for i in range(len(my_list)):
        min=my_list[i]
        min_loc=i

        for j in range(i+1,len(my_list)):
            if min>my_list[j]:
                min=my_list[j]
                min_loc=j
        temp=min
        my_list[min_loc]=my_list[i]
        my_list[i]=temp
    print(my_list)
list1(a_list)

#task-3:
my_list = [10, 1, 20, 3, 6, 2, 5, 11, 15, 2, 12, 14, 17, 18, 29]
for i in range(len(my_list)):
    min=my_list[i]
    min_loc=i

    for j in range(i+1,len(my_list)):
        if min<my_list[j]:
            min=my_list[j]
            min_loc=j
    temp=min
    my_list[min_loc]=my_list[i]
    my_list[i]=temp
print(my_list)

#task-3:
my_list = [10, 1, 20, 3, 6, 2, 5, 11, 15, 2, 12, 14, 17, 18, 29]
for i in range(len(my_list)):
    min=my_list[i]
    min_loc=i

    for j in range(i+1,len(my_list)):
        if min<my_list[j]:
            min=my_list[j]
            min_loc=j

    temp=min
    print(temp)
    my_list[min_loc]=my_list[i]
    my_list[i]=temp
print(my_list)

#task-4:
sitting_list = [10,30,20,70,11,15,22,16,58,100,12,56,70,80]

even_index=[]
odd_index=[]
new=[]

for counting_mach in range(0,len(sitting_list)):
    if counting_mach%2==0:
        even_index.append(sitting_list[counting_mach])
    else:
        odd_index.append(sitting_list[counting_mach])

even_value=sorted(even_index,reverse=False)
odd_value=sorted(odd_index,reverse=True)

for counter_x in range(0,len(even_value)):
     new.append(even_value[counter_x])
     new.append(odd_value[counter_x])

print("The new list:",new)

#task-4:
sitting_list = [10,30,20,70,11,15,22,16,58,100,12,56,70,80]
for i in range(len(sitting_list)):
    min=sitting_list[i]
    min_loc=i
    
    for j in range(len(sitting_list)):
        if min>my_list[j]:
            min=my_list[j]
            min_loc=j
    temp=min
    my_list[min_loc]=my_list[i]
    my_list[i]=temp
  print(temp)

#task-5:
total_students=int(input('Sir, please enter your number: '))
a_list=[]
for count in range(0, total_students):
    name=input()
    CSE110=int(input())
    PHY111=int(input())
    MAT110=int(input())
    a_list.append([name,CSE110,PHY111,MAT110])
    print('The final list is: ', a_list)
course_code=input()
if course_code=='CSE110':
    index=1
elif course_code=='PHY111':
    index=2
elif course_code=='MAT110':
    index=3

#selection sorting
max_list=[]
for count in range(0, len(a_list)):
    max=a_list[count][index]
    max_loc=count
for i in range(count+1, len(a_list)):
    if a_list[i]<max:
        max=a_list[i]
        max_loc=i
        temp=max_list
    a_list[max_loc]=a_list[count]
    a_list[count]=temp
for count in range(0, len(a_list)):
    print(a_list[count][0])



#task-6:
my_list = [4, 2, 3, 1, 6, 5]
new_list=my_list.copy()
for i in range(len(my_list)):
    for j in range(len(my_list)-i-1):
        if my_list[j]>my_list[j+1]:
            temp=my_list[j]
            my_list[j]=my_list[j+1]
            my_list[j+1]=temp
print(my_list)
count=0
for k in range(len(my_list)):
    if my_list[k]!=new_list[k]:
        count=count+1

print(f'The number of swaps {count}')   #alternative of .formate

#task-6:
my_list = [4, 2, 3, 1, 6, 5]
new_list=my_list.copy()
for i in range(len(my_list)):
    for j in range(len(my_list)-i-1):
        if my_list[j]>my_list[j+1]:
            temp=my_list[j]
            my_list[j]=my_list[j+1]
            my_list[j+1]=temp
print(my_list)
count=0
for k in range(len(my_list)):
    if my_list[k]!=new_list[k]:
        count=count+1

print('The number of {} swaps'.format(count))   #alternative of .formate

#task-7:
list_one = [1, 2, 1, 4]
list_two = [5, 4, 1]
my_list=list_one+list_two
print(my_list)

for i in range(len(my_list)):
    for j in range(len(my_list)-i-1):
        if my_list[j]>my_list[j+1]:
            temp=my_list[j]
            my_list[j]=my_list[j+1]
            my_list[j+1]=temp
print(my_list)
length=len(my_list)
if length%2!=0:
    median=my_list[((length+1)//2)-1]
    print(median)
else:
    median=my_list[(((length//2)-1)+(((length+1)//2)-1)//2)-1]
    print(median)

list_one = [1, 7, 9, 10]
list_two = [2, 7, 6, 5]

my_list=list_one+list_two
print(my_list)

for i in range(len(my_list)):
    for j in range(len(my_list)-i-1):
        if my_list[j]>my_list[j+1]:
            temp=my_list[j]
            my_list[j]=my_list[j+1]
            my_list[j+1]=temp
print(my_list)
length=len(my_list)
if length%2!=0:
    median=my_list[((length+1)//2)-1]
    print(median)
else:
    median=my_list[(((((length//2)-1)+((length//2)+1)-1))/2)]
    print(median)

#task-7:
list_one = [1, 7, 9, 10]
list_two = [2, 7, 6, 5]

my_list=list_one+list_two
print(my_list)

for i in range(len(my_list)):
    for j in range(len(my_list)-i-1):
        if my_list[j]>my_list[j+1]:
            temp=my_list[j]
            my_list[j]=my_list[j+1]
            my_list[j+1]=temp
print(my_list)
length=len(my_list)
if length%2!=0:
    median=my_list[((length+1)//2)-1]
    print(median)
else:
    median1=my_list[length//2]
    median2=my_list[length//2-1]
    median=(median1+median2)/2
    print(median)

#task-8:
x_first = int(input('Sir,enter the length of list one: '))
list_a=[]

for count in range(0,x_first):
   user_value=int(input('Sir,enter your desired value: '))
   list_a.append(user_value)

print("The list is:",list_a)
diff=abs(list_a[0]+list_a[1])
x=0
y=0
z=1000
for p in range(len(list_a)):
    for q in range(len(list_a)-1):
        if (p!=q):
            z=abs(list_a[p]+list_a[q])
        if(z<diff):
            diff=z
            x=list_a[p]
            y=list_a[q]
print('Two pairs which have the smallest sum = ',x,'and',y)

#task-9: