# -*- coding: utf-8 -*-
"""Lab Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jmi6_QeN8hHKBGNl08vLyHJdwSgZeRfY
"""

number_1=int(input('please enter the first number: '))
number_2=int(input('please enter your second number: '))
total=number_1+number_2
difference=number_1-number_2
product=number_1*number_2

print("Sum=", total)
print("Product=", product)
print("Difference=", difference)

import math
radius=float(input('please enter your number: '))
area=math.pi*radius**2
circumference=2*math.pi*radius

print("Area is=", area)
print("Circumference is=", circumference)

fnumber=int(input('please enter your first number: '))
snumber=int(input('please enter your second number: '))

if fnumber>snumber:
  print('First is greater')

fnumber=int(input('please enter your first number: '))
snumber=int(input('please enter your second number: '))

if fnumber>snumber:
  print('First is greater')
elif snumber>fnumber:
  print('Second number is greater')
else:
  print('The numbers are equal')

fnumber=int(input('please enter your first number: '))
snumber=int(input('please enter your second number: '))

if fnumber>snumber:
   subtract=fnumber-snumber
elif snumber>fnumber:
   subtract=snumber-fnumber
else:
  subtract=fnumber-snumber
print(subtract)

number=int(input('please enter your first number: '))

if number %2==0:
  print('The number is even')
else:
  print('The number is odd')

number=int(input('please enter your number: '))
if number %2==0 or number %5==0:
  print(number)
else:
  print('Not a multiple of 2 or 5')

number=int(input('please enter your number: '))
if number %2==0 and number %5==0:
  print('Mulitple of 2 and 5 both')
elif number %2==0 or number %5==0:
  print(number)
else:
  print('Not a mulitple we want')

number=int(input('please enter your number: '))
if number %2==0 and number %5==0:
  print(number)
else:
  print('Not a mulitple of 2 and 5 both')

var1 = var2 = var3 = var4 = var5 = var6 = False
result1 = False
result2 = False
result3 = False
result4 = False
result5 = False
result6 = False
result7 = False
result8 = False
result9 = False
result10 = False
var1 = 4 > 3 - 1
var2 = var1 and False
var3 = True
var4 = False
var5 = True
var6 = var3 and False
result1 = (var1 or var2) and (8 * 10 > 45)
result2 = (var1 or var2) and (result1 and False)
result3 = (var1 and result1) or result2
result4 = (var1 or var2) or ((var3 and var1) and False)
result5 = (var1 and var2) and (result3 or var1)
result6 = ((var3 or var2) and not(result5)) or True
result7 = (var4 and result1) and ((result1 and False) or True)
result8 = ((var1 and result3) and (var5 or var6)) and True
result9 = ((result2 and var2) or (result7 and var1)) and False
result10 = not(var1 and True)

print(result1)
print(result2)
print(result3)
print(result4)
print(result5)
print(result6)
print(result7)
print(result8)
print(result9)
print(result10)

var1 = False
var2 = False
var3 = False
var4 = False
var5 = False
var6 = False
result1 = False
result2 = False
result3 = False
result4 = False
result5 = False
result6 = False
result7 = False
result8 = False
result9 = False
result10 = False
var1 = ((not True) or True) and False
var2 = var1 and False
var3 = True and not False
var4 = False
var5 = True
var6 = var3 and False
result1 = (var1 and var2) and (40 % 3) > 45 or (var5 and var6)
result2 = (var1 or var2) or (result1 and False)
result3 = (var1 and result1) or result2 or var5
result4 = (var1 or var2) or ((var3 and var1) and False)
result5 = (var1 and var2) and (result3 or var1)
result6 = ((var3 or (not var2)) and (result5)) or True
result7 = (var4 and result1) and ((result1 and False) or True)
result8 = ((var1 and result3) and ((not var5) or var6)) and True
result9 = ((result2 and var2) or ((not result7) and var1)) and not False
result10 = not(var1 and True)

print(result1)
print(result2)
print(result3)
print(result4)
print(result5)
print(result6)
print(result7)
print(result8)
print(result9)
print(result10)

var1 = var2 = var3 = var4 = var5 = var6 = False
result1 = result2 = result3 = result4 = result5 = result6 = False
result7 = result8 = result9 = result10 = False
var1 = (not False or False) and True
var2 = var1 and True
var3 = False and not True
var4 = True
var5 = False
var6 = var3 and True
result1 = (var1 and var2) and ( 40 % 3 > 45) or (var5 and var6)
result2 = (var1 or var2) or (result1 and False)
result3 = (var1 and result1) or result2 or var5
result4 = (var1 or var2) or ((var3 and var1) and False)
result5 = (var1 and var2) and (result3 or var1)
result6 = ((var3 or not var2) and (result5)) or True
result7 = (var4 and result1) and ((result1 and False) or True)
result8 = ((var1 and result3) and (not var5 or var6)) and True
result9 = ((result2 and var2) or (not result7 and var1)) and not False
result10 = not (var1 and True)

print(result1)
print(result2)
print(result3)
print(result4)
print(result5)
print(result6)
print(result7)
print(result8)
print(result9)
print(result10)

p = 5
q = 6
r = 9
sum = 0
if (p < 12):
  print(r + 2)
else:
  print(r + p)
if (q > 20):
  print(r + 19)
elif (q <= 6):
  print(q + 3)
else:
  print(p + q + r)
if (r > 15):
  print(r)
elif (r == 0):
  print(p + q)
else:
  print(p)
if (sum != 0):
  print(3)
else:
  print(sum + 32)
if (p>0 and r<10):
  print(p+r)
else:
  print(p-r)

time= int(input('Please enter the amount of seconds: '))
hour= time//3600
remainder= time%3600
mins= remainder//60
sec= remainder%60

print('Hours: ', hour, 'Minutes: ', mins,'Seconds: ', sec)

Hour: int(input('Please enter the amount of seconds: '))

if hour<0 or hour>168:
  print('Hour cannot be negative')
elif hour>168:
  print('Impossible to work more than 168 hours')
elif hour <=40:
  salary=hour*200
  print(salary)
else:
  salary=8000+(hour-40)*300

print(salary)

time=int(input('Please enter your amount of seconds: '))
hour=time//3600
remainder=time%3600
mins=remainder//60
sec=remainder%60
print('Hours:', hour, 'Minutes:', mins, 'Seconds:', sec)

hour= int(input('Please enter your amount of hour: '))
if hour<0:
  print('Hour cannot be negative')
elif hour>168:
   print('Impossible to work more than 168 hours')
elif hour<=40:
  salary=hour*200
  print(salary)
else:
  salary= 8000+(hour-40)*300
  print(salary)

import math
S=int(input('Please enter your number: '))
if S<100:
  L=3000-(125*math.pow(S,2))
elif S>=100:
  L=12000/(4+(math.pow(S,2))/14900)

print('The value of L:', L)

time =int(input('Please insert your number: '))
if time>=4 and time<=6:
  print('Breakfast')
elif time>=12 and time<=13:
  print('Lunch')
elif time>=16 and time<=17:
  print('Snacks')
elif time>=19 and time<=20:
  print('Dinner')
elif (hour>=0 and hour<=4) or (hour>=7 and hour<=12) or (hour>=14 and hour<16) or (hour>=18 and hour<=19) or (hour>=20 and hour<24):
  print('Patience is a virtue')
else:
  print('Wrong time')

hour=int(input("Sir,please enter your desired hour: "))
if hour>=0 and hour<=23:
    if hour>=4 and hour<=6 :
        print("Breakfast")
    elif hour>=12 and hour<=13:
        print("Lunch")
    elif hour>=16 and hour<=17:
        print("Snacks")
    elif hour>=19 and hour<=20:
        print("Dinner")
    elif (hour>=0 and hour<4) or (hour>=7 and hour<12) or (hour>=14 and hour<16) or (hour>=18 and hour<19) or (hour>=20 and hour<24):
        print("Patience is virtue: ")
else:
  print("Wrong time")

number=int(input('Please enter your number: '))
if number>=0 and number<50:
  print('F')
elif number>=50 and number<=59:
  print('E')
elif number>=60 and number<=69:
  print('D')
elif number>=70 and number<=79:
  print('C')
elif number>=80 and number<=89:
  print('B')
elif number>=90 and number<=100:
  print('A')
else:
  print('Invalid')

distance=int(input('Please enter your distance: '))
time= int(input('Please enter your time: '))
distance_km= distance/1000
hour=time/3600
velocity=distance_km/hour
print(velocity)
if velocity<60:
   print('Too slow, Needs more changes')
elif velocity >=60 and velocity<=90:
  print('Velocity is okay. The car is ready!')

number=float(input('Please enter your grades: '))
credit=int(input('Please enter your credit number: '))
if credit>=30 and number>=3.80 and number<=3.89:
  print('The student is eligible for a waiver of 25 percent')
elif credit>=30 and number>=3.90 and number<=3.94:
  print('The student is eligible for a waiver of 50 percent')
elif credit>=30 and  number<=3.95 and number>=3.99:
  print('The student is eligible for a waiver of 75 percent')
elif credit>=30 and number==4.00:
  print('The Student is eligible for a waiver of 100 percent')
else:
  print('The student is not eligible for a waiver')

def fizzBuzz(n):
    for i in range(0,n):
        if n[i]%3==0 and n[i]%5==0:
            print('FizzBuzz')
        elif n[i]%3==0:
            print('Fizz')
        elif n[i]%5==0:
            print('Buzz')
        else:
            print(n[i])            
fizzBuzz(10)