# -*- coding: utf-8 -*-
"""Lab Assignment 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yWyDH7tUfJa3GZ35ZSzTVDHlY8ibMskg
"""

print('Hello this is Tasrif Coding')

#Theory Mid solve:
word=input()
upper=''
lower=''
digit=''
special=''
new_word=''
for i in word:
    if 65<=ord(i)<=90:
        upper=upper+i
    elif 97<=ord(i)<=122:
        lower=lower+i
    elif 48>=ord(i)<=57:
        digit=digit+i
    else:
        if i=='':
            pass
        else:
            special=special+i

for i in range(len(upper)):        #As the length of all the same characters are same therefore we can pick any of them.
    new_word=new_word+upper[i]+lower[i]+digit[i]+special[i]
print(new_word)

"""Tuple"""

a_tuple=(1,2,3,[1,2,34,54], 'Tasrif Khan', 12.333434)
print(a_tuple)

new_tuple=((1,2,3,[1,2,34,54], 'Tasrif Khan', 12.333434), 'Block-f, Road-2, House-14, Rampura, Banasree')
print(new_tuple)

"""List

"""

a_list=[1,2,3,4,54,(1,2,3.22,'Banasree'), 'Tasrif']
print(a_list)

new_list=[[1,2,3,4,54,(1,2,3.22,'Banasree'), 'Tasrif'],'Block-f, Road-2, House-14, Rampura, Banasree']
print(new_list)

name='Tasrif'
task='reviewer'

print('This is', name, ', I am a laptop also a tech', task)

name='Tasrif'
task='reviewer'

print('This is', name+ ', I am a laptop also a tech', task+'.')

name='Tasrif'
task='reviewer'

print('This is {}, I am a laptop also a tech {}.' . format(name, task))

"""Assignment-5:"""

#task-1:
a_tuple=("The Institute", ("Best Mystery & Thriller", "The Silent Patient", 68821), 75717,
[1, 2, 3, 400, 5, 6, 7], ("Best Fiction", "The Testaments", 98291))
print(a_tuple[3][3])

#task-2:
a_tuple=(10, 20, 24, 25, 26, 35, 70)
print(a_tuple[2:len(a_tuple)-2])

#task-3:
book_info = (
("Best Mystery & Thriller","The Silent Patient",68,821),
("Best Horror","The Institute",75,717),
("Best History & Biography","The five",31,783 ),
("Best Fiction","The Testaments",98,291)
)
length=len(book_info)
print(length)

#task-4:
book_info = (
("Best Mystery & Thriller","The Silent Patient",68821),
("Best Horror","The Institute",75717),
("Best History & Biography","The five",31783 ),
("Best Fiction","The Testaments",98291)
)
length=len(book_info)
print(length)
for i in book_info:
    print(i)

#task-4:
book_info = (
("Best Mystery & Thriller","The Silent Patient",68821),
("Best Horror","The Institute",75717),
("Best History & Biography","The five",31783 ),
("Best Fiction","The Testaments",98291)
)

for award,name,vote in book_info:
    print('The {} won the {} category with {} votes'.format(name,award,vote) )


#The Silent Patient won the 'Best Mystery & Thriller' category with 68821 votes
#The Institute won the 'Best Horror' category with 75717 votes
#The five won the 'Best History & Biography' category with 31783 votes
#The Testaments won the 'Best Fiction' category with 98291 votes

#task-5:
a_tuple=(10, 8, 5, 2, 10, 15, 10, 8, 5, 8, 8, 2)
user= int(input('Please enter your desired number: '))
counter=0
for i in a_tuple:
    if i==user:
        counter=counter+1
print('{} appears {} times in the tuple'.format(user, counter))

#task-6:
a_tuple=('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h')
a_list=list(a_tuple)
print(a_list)

new_tuple=(a_list[-1: :-1])
print('The new list is: ',new_tuple)

final_tuple=tuple(new_list)
print('The final tuple is: ',final_tuple)

-17%8

#task-6:
a_list=[]
a_tup=('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h')
for i in range(len(a_tup)-1,-1,-1):
    a_list.append(a_tup[i])
print(tuple(a_list))

new_tuple=([1,2,3,4.5,5])
print(type(new_tuple))

"""Dictionary

```
# This is formatted as code
```

Dictionary defines basically key:value and we consider this whole thing as an item
"""

a_dict={21301351:'Tasrif'}
b_dict={'Fredrick':33333}

new_dict={1:'one', 2:'two', 3:'three', 4:'four'}
print(new_dict)

abcd_dict={}
abcd_dict['car']=['Audi A8']
print(abcd_dict)

abcd_dict={}
abcd_dict['car']='Audi A8'
print(abcd_dict)
abcd_dict['watch']='Rolex'
print(abcd_dict)

bd_dict={}
bd_dict['car','watch']=['Audi A8', 'Rolex']
print('The new dictionary is: ', bd_dict)

ab_dict={'Harry':15, 'Draco':8, 'Nevil':19}

for key,value in ab_dict.items():
    print('Key is: ', key)
    print('Value is: ', value)

bb_dict={'Harry':15, 'Draco':8, 'Nevil':19}
print(bb_dict.items())

#task-7:
a_dict={'Harry':15, 'Draco':8, 'Nevil':19}
b_dict={'Ginie': 18, 'Luna': 14}

marks={}
for key,value in a_dict.items():
    marks[key]=value
for key,value in b_dict.items():
    marks[key]=value
print(marks)

#task-8(correct one):
user=input("please enter your dictionary: ")
dict_str=user[1:-1]
dict_list=dict_str.split(',')
print(dict_list)
dict5=dict()
for item in dict_list:
    print(item)
    temp_list=item.split(':')
    key=temp_list[0].strip('/')
    print('Key= ',key)
    value=int(temp_list[1])
    print('Value= ', value)
    dict5[key]=value
print(dict5)

sum=0
for key,value in dict5.items():
    sum=sum+value

print('The average is: ',int(sum/len(dict5)))

#task-8(extra):
a_dict={'Jon': 100, 'Dan':200, 'Rob':300}
for count in range(0,3):
    key=input("enter key: ")
    value=int(input("enter value: "))
    a_dict[key]=value
print(a_dict)
hold=a_dict.values()
a_list=list(hold)
print(a_list)
total=0
for count in range(0,len(a_list)):
    total=total+a_list[count]
average=total/len(a_list)
print('The average is: ',average)

number=int(input())
sum=3
for n in range(1,number+1):
    if n%7==0:
        sum=sum+number
print(sum)

(8%6)

#task-9:
user_key=input('Please enter your desired key: ')
user_value=input('Please enter your desired value: ')
a_list=[]
for key,value in item(0,1):
    a_list.append(user_key,user_value)
print(a_list)

#task-9: 
exam_marks = {'Cierra Vega': 175, 'Alden Cantrell': 200, 'Kierra Gentry': 165, 'Pierre Cox': 190}
user=int(input('Sir please enter your desired number: '))
new_dict={}

for key,value in exam_marks.items():
    if value>user:
        new_dict[key]=value
print(new_dict)

#task-10:
a_dict={'sci fi': 12, 'mystery': 15, 'horror': 8, 'mythology': 10, 'young_adult': 4, 'adventure':14}
max_value=0
max_key=''
for key,value in a_dict.items():
    if value>max_value:
        max_value=value
        max_key=key
print('The highest selling book genre is "{}" and the number of books sold are {}.'. format(max_key,max_value))

new_dict={}
new_dict['p']=1
print(new_dict)
new_dict['p']+=1
print(new_dict)
new_dict['p']+=1
print(new_dict)

a_dict={'car':'Audi A8'}
print(a_dict)

a_dict={'car':'Audi A8'}
print(a_dict['car'])

#task-11:
user="Python programming is fun"
small=user.lower()
print(small)
nword=''
for count in small:
    if count!=' ':
        nword+=count
print(nword)

new_dict={}
for i in nword:
    if i not in new_dict:
        new_dict[i]=1
    else:
        new_dict[i]+=1
print(new_dict)

#task-11:  (self Tryout)

user=str(input('Sir, please enter your desired word: '))
small=user.lower()
print(small)

add=''
for count in small:
    if count!=' ':
       add+=count
print(add)

new_dict={}
for i in add:
    if i not in new_dict:
        new_dict[i]=1
    else:
        new_dict[i]+=1
print(new_dict)

#task-12:
dict_1 = {'A': [1, 2, 3], 'b': ['1', '2'], "c": [4, 5, 6, 7]}
counter=0
for key,value in dict_1.items():
    for i in value: 
        counter=counter+1
print(counter)

dict_1 = {'A': [1, 2, 3], 'b': ['1', '2'], "c": [4, 5, 6, 7]}
print(dict_1.values())

dict_1 = {'A': [1, 2, 3], 'b': ['1', '2'], "c": [4, 5, 6, 7]}
print(dict_1.keys())

dict_1 = {'A': [1, 2, 3], 'b': ['1', '2'], "c": [4, 5, 6, 7]}
print(dict_1.items())

list_1 = [("a", 1), ("b", 2), ("a", 3), ("b", 1), ("a", 2), ("c", 1)]

add=''
list_a=[]
list_b=[]
list_c=[]

for i in list_1:
    if i[0]=='a':
        list_a.append(i[1])
    elif i[0]=='b':
        list_b.append(i[1])
    else:
        list_c.append(i[1])
print(list_a)
print(list_b)
print(list_c)

new_dict={'a':list_a, 'b': list_b, 'c ': list_c}
print(new_dict)

#task-13:
list_1 = [("a", 1), ("b", 2), ("a", 3), ("b", 1), ("a", 2), ("c", 1)]
list_a=[]
list_b=[]
list_c=[]
for i in list_1:
    if i[0]=='a':
        list_a.append(i[1])
    elif i[0]=='b':
        list_b.append(i[1])
    elif i[0]=='c':
        list_c.append(i[1])
    
new_dict={'a': list_a, 'b':list_b, 'c':list_c}
print(new_dict)

#task-14:
dict1 = {'a':59 , 'b':-82 , 'c':5 , 'd':-81 , 'e':53}
for i in dict1:
    j = 0
    k = 22
    while j < 5:
        if j % 2 == 0:
            k = dict1[i] + j - (8 + k % 6) / 3
            dict1[i] = dict1[i]+ int(k)
        else:
            k = dict1[i] + j - (6 - k % 8) * 3
            dict1[i] = dict1[i] - int(k)
        j += 1
    print(int(k))
    print(i + " -> " + str(dict1[i]))

(6-19%6)

(-19%6)

5-19%6

8.6667%6

k = 114 + 1 - (6 - 55.0 % 8) * 3
print(k)

"""Ungraded tasks(15-19):"""

#task-15:
a_list=[(2, 3), (4, 5), (6, 7), (2, 8)]
list1=[]
list2=[]
list3=[]
new_list=[]
for i in a_list:
    if i[1]==3:
        list1.append(i[1]*2)
    elif i[1]==5:
        list2.append(i[1]*4)
    elif i[1]==7:
        list3.append(i[1]*6)
print(list1,list2,list3)
new_list=list1,list2,list3
print(new_list)

#task-17:
a_dict={'c1':'Red', 'c2':'Green', 'c3':None, 'd4':'Blue', 'a5':None}
new_dict={}
for key,value in a_dict.items():
    if value==None:
        pass
    else:
        new_dict[key]=value
print(new_dict)

#task-18:
user1=int(input('Sir, please enter your desired number: '))
user2=int(input('Sir, please enter your desired number: '))
dict1={'a' : 6, 'b' : 7, 'c' : 9, 'd' : 8, 'e' : 11, 'f' : 12, 'g' : 13}
new_dict={}

for key,value in dict1.items():
    if value>=user1 and value<user2:
        new_dict[key]=value

print(new_dict)

#task-19:
a_list=[(20, 80), (31, 80), (1, 22), (88, 11), (27, 11)]
list1=[]
list2=[]
list3=[]
new_dict={}

for i in a_list:
    if i[1]==80:
        list1.append(i)
    elif i[1]==11:
        list2.append(i)
    else:
        list3.append(i)
print(list1)
print(list2)
print(list3)
for a in a_list:
    if a[1]==80:
        new_dict[a[1]]=list1
    elif a[1]==11:
        new_dict[a[1]]=list2
    else:
        new_dict[a[1]]=list3
print(new_dict)

#task-20:
words='I love Programming. Python is love.'
a_list=['c','$','&','#']
dummy=''
b_list=[]
length=len(a_list)
for i in words:
    if i=='.':
        pass
    else:
        dummy=dummy+i
print(dummy)
 
var1=dummy.split(' ')
print(var1)

for a in var1:
    if a not in b_list:
        b_list.append(a)
print(b_list)

sum=0
new_dict={}
for j in b_list:
    for k in j:
        sum=sum+ord(k)
    print(sum)

    index=sum%length
    if a_list[index] not in new_dict:
        new_dict[a_list[index]]=[j]
    else:
        new_dict[a_list[index]].append(j)
    sum=0
    print(new_dict)

user=str(input())
def transformSentence(sentence):
    new_word=''
   # for i in range(len(sentence)):
     #   if i==0:
     #       new_word=new_word+sentence[i]
     #   elif sentence[i].islower:
     #           new_word=new_word+sentence[i].upper()
    #print(new_word)  

    for i in range(len(sentence)):
            if i==0:
                new_word=new_word+sentence[i]
            elif i==5:
                new_word=new_word+sentence[i]
            elif i==10:
                new_word=new_word+sentence[i].lower()
            elif sentence[i].islower:
                new_word=new_word+sentence[i].upper()
    print(new_word)
transformSentence(user)